[tool.poetry]
name = "my_agent"
version = "0.2.0"
description = "Example LangGraph project for deployment to LangGraph Cloud"
authors = [
    "langchain-ai"
]
packages = [
    { include = "my_agent" },
]

[tool.poetry.dependencies]
python = ">=3.9.0,<3.13"
langgraph = "^0.5.1"
langchain-anthropic = "^0.3.17"
langchain-core = "^0.3.68"
langchain-openai = "^0.3.27"
langchain-community = "^0.3.27"
PyGithub = "^2.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
#test
